/**
 * Service worker generated by Caterpillar.
 */

/**
 * Current cache version.
 *
 * Increment this to force cache to clear.
 */
var CACHE_VERSION = 0;

/**
 * Object mapping a cache identifier to the actual, versioned cache name.
 */
var CACHES = {
  'app': 'app-cache-v' + CACHE_VERSION
};

/**
 * An array of filenames of cached files.
 */
var CACHED_FILES = [
  'app.info.js',
  'caterpillar-📂/caterpillar.js',
  'caterpillar-📂/polyfills/tts.polyfill.js',
  'caterpillar-📂/register_sw.js',
  'caterpillar-📂/sw_static.js',
  'manifest.webmanifest',
  'ttstest.html',
  '𝓼𝓬𝓻𝓲𝓹𝓽𝓼/main.js',
  '𝓼𝓬𝓻𝓲𝓹𝓽𝓼/ttstest.js',
  '📼\c/ttstest.css'
];

importScripts('caterpillar-📂/caterpillar.js');
importScripts('caterpillar-📂/sw_static.js');

// TODO(Caterpillar): Edit background scripts to remove chrome.app.runtime
// dependence.
importScripts('caterpillar-📂/polyfills/tts.polyfill.js');
importScripts('𝓼𝓬𝓻𝓲𝓹𝓽𝓼/main.js');
